controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    differential_drive_controller:
      type: differential_drive_controller/DifferentialDriveController

differential_drive_controller:
  ros__parameters:
    command_topic: /cmd_vel
    command_type: velocity
    feedback_types: ["velocity", "position"]
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]

    wheels_per_side: 2
    wheel_separation: 0.350
    wheel_radius: 0.1

    odom_frame_id: "odom"
    base_frame_id: base_link

    is_open_loop: false
    command_timeout: 1.0
